/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AccesoBibliografia: typeof import('./src/components/AccesoBibliografia.vue')['default']
    AppHeader: typeof import('./src/components/AppHeader.vue')['default']
    BarraBusqueda: typeof import('./src/components/BarraBusqueda.vue')['default']
    CuerpoHumano: typeof import('./src/components/CuerpoHumano.vue')['default']
    MenuDropdown: typeof import('./src/components/MenuDropdown.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
