/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppHeader: typeof import('./src/components/AppHeader.vue')['default']
    BarraBusqueda: typeof import('./src/components/BarraBusqueda.vue')['default']
    CuerpoHumano: typeof import('./src/components/CuerpoHumano.vue')['default']
    DiagnosticsHelper: typeof import('./src/components/DiagnosticsHelper.vue')['default']
    EditorAdmin: typeof import('./src/components/EditorAdmin.vue')['default']
    FloatingDiagnostics: typeof import('./src/components/FloatingDiagnostics.vue')['default']
    MenuDropdown: typeof import('./src/components/MenuDropdown.vue')['default']
    PanelContenidoCuerpo: typeof import('./src/components/PanelContenidoCuerpo.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SemiologiaCabezaCuello: typeof import('./src/components/info/SemiologiaCabezaCuello.vue')['default']
  }
}
